## Week 3 - Manipulación de Datos con Python

### Filtrado, Agrupación y Merge de Datos

Crear datasets relacionados:

In [ ]:
import pandas as pd
import numpy as np

# Dataset de ventas
ventas = pd.DataFrame({
    'id_venta': range(1, 11),
    'id_cliente': np.random.choice([1, 2, 3, 4, 5], 10),
    'id_producto': np.random.choice([101, 102, 103, 104], 10),
    'cantidad': np.random.randint(1, 5, 10),
    'fecha': pd.date_range('2024-01-01', periods=10, freq='D')
})

# Dataset de clientes
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4, 5],
    'nombre': ['Ana', 'Carlos', 'María', 'Juan', 'Luis'],
    'ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Valencia', 'Sevilla']
})

# Dataset de productos
productos = pd.DataFrame({
    'id_producto': [101, 102, 103, 104],
    'nombre': ['Laptop', 'Mouse', 'Teclado', 'Monitor'],
    'precio': [1200, 25, 80, 300],
    'categoria': ['Electrónica', 'Accesorios', 'Accesorios', 'Electrónica']
})

print("Datasets creados:")
print(f"Ventas: {ventas.shape}")
print(f"Clientes: {clientes.shape}")
print(f"Productos: {productos.shape}")

Datasets creados:
Ventas: (10, 5)
Clientes: (5, 3)
Productos: (4, 4)

Filtrado avanzado con query():

In [ ]:
print(ventas.head(), "\n")
print(productos.head())

   id_venta  id_cliente  id_producto  cantidad      fecha
0         1           1          103         2 2024-01-01
1         2           3          102         3 2024-01-02
2         3           2          103         1 2024-01-03
3         4           1          103         3 2024-01-04
4         5           3          104         3 2024-01-05

   id_producto   nombre  precio    categoria
0          101   Laptop    1200  Electrónica
1          102    Mouse      25   Accesorios
2          103  Teclado      80   Accesorios
3          104  Monitor     300  Electrónica

In [ ]:
# Ventas del mes actual con query
ventas_recientes = ventas.query('fecha >= "2024-01-05"')
print(f"\nVentas recientes: {len(ventas_recientes)}")

# Productos caros usando variable externa
precio_limite = 100
productos_caros = productos.query('precio >= @precio_limite')
print(f"Productos caros (>= {precio_limite}): {productos_caros['nombre'].tolist()}")

Ventas recientes: 6
Productos caros (>= 100): ['Laptop', 'Monitor']

Agrupación y agregación:

In [ ]:
print(ventas.head())

   id_venta  id_cliente  id_producto  cantidad      fecha
0         1           1          103         2 2024-01-01
1         2           3          102         3 2024-01-02
2         3           2          103         1 2024-01-03
3         4           1          103         3 2024-01-04
4         5           3          104         3 2024-01-05

In [ ]:
# Ventas por producto
ventas_por_producto = ventas.groupby('id_producto')['cantidad'].sum()
print(f"\nVentas por producto:\n{ventas_por_producto}")

# Estadísticas por cliente
stats_por_cliente = ventas.groupby('id_cliente').agg({
    'cantidad': ['sum', 'mean'],
    'id_venta': 'count'
})
print(f"\nEstadísticas por cliente:\n{stats_por_cliente}")

Ventas por producto:
id_producto
101    6
102    6
103    6
104    6
Name: cantidad, dtype: int64

Estadísticas por cliente:
           cantidad           id_venta
                sum      mean    count
id_cliente
1                 6  2.000000        3
2                 7  2.333333        3
3                 6  3.000000        2
4                 5  2.500000        2

Merge para análisis completo:

In [ ]:
# Unir ventas con productos
ventas_productos = pd.merge(ventas, productos, on='id_producto')

# Calcular totales
ventas_productos['total'] = ventas_productos['cantidad'] * ventas_productos['precio']

# Unir con clientes
#analisis_completo = pd.merge(ventas_productos, clientes, on='id_cliente')
analisis_completo = pd.merge(ventas_productos, clientes, on='id_cliente', suffixes=('_producto', '_cliente'))

print(f"\nAnálisis completo (primeras 5 filas):\n{analisis_completo.head()}")

# Análisis por ciudad
ventas_por_ciudad = analisis_completo.groupby('ciudad')['total'].sum()
print(f"\nVentas totales por ciudad:\n{ventas_por_ciudad}")

Análisis completo (primeras 5 filas):
   id_venta  id_cliente  id_producto  cantidad      fecha nombre_producto  \
0         1           1          103         2 2024-01-01         Teclado
1         2           3          102         3 2024-01-02           Mouse
2         3           2          103         1 2024-01-03         Teclado
3         4           1          103         3 2024-01-04         Teclado
4         5           3          104         3 2024-01-05         Monitor

   precio    categoria  total nombre_cliente     ciudad
0      80   Accesorios    160            Ana     Madrid
1      25   Accesorios     75          María     Madrid
2      80   Accesorios     80         Carlos  Barcelona
3      80   Accesorios    240            Ana     Madrid
4     300  Electrónica    900          María     Madrid

Ventas totales por ciudad:
ciudad
Barcelona    7280
Madrid       1400
Valencia      950
Name: total, dtype: int64

In [ ]:
ventas_productos

,id_venta,id_cliente,id_producto,cantidad,fecha,nombre,precio,categoria,total
0,1,1,103,2,2024-01-01,Teclado,80,Accesorios,160
1,2,3,102,3,2024-01-02,Mouse,25,Accesorios,75
2,3,2,103,1,2024-01-03,Teclado,80,Accesorios,80
3,4,1,103,3,2024-01-04,Teclado,80,Accesorios,240
4,5,3,104,3,2024-01-05,Monitor,300,Electrónica,900
5,6,1,102,1,2024-01-06,Mouse,25,Accesorios,25
6,7,2,101,3,2024-01-07,Laptop,1200,Electrónica,3600
7,8,4,102,2,2024-01-08,Mouse,25,Accesorios,50
8,9,2,101,3,2024-01-09,Laptop,1200,Electrónica,3600
9,10,4,104,3,2024-01-10,Monitor,300,Electrónica,900

In [ ]:
analisis_completo

,id_venta,id_cliente,id_producto,cantidad,fecha,nombre_producto,precio,categoria,total,nombre_cliente,ciudad
0,1,1,103,2,2024-01-01,Teclado,80,Accesorios,160,Ana,Madrid
1,2,3,102,3,2024-01-02,Mouse,25,Accesorios,75,María,Madrid
2,3,2,103,1,2024-01-03,Teclado,80,Accesorios,80,Carlos,Barcelona
3,4,1,103,3,2024-01-04,Teclado,80,Accesorios,240,Ana,Madrid
4,5,3,104,3,2024-01-05,Monitor,300,Electrónica,900,María,Madrid
5,6,1,102,1,2024-01-06,Mouse,25,Accesorios,25,Ana,Madrid
6,7,2,101,3,2024-01-07,Laptop,1200,Electrónica,3600,Carlos,Barcelona
7,8,4,102,2,2024-01-08,Mouse,25,Accesorios,50,Juan,Valencia
8,9,2,101,3,2024-01-09,Laptop,1200,Electrónica,3600,Carlos,Barcelona
9,10,4,104,3,2024-01-10,Monitor,300,Electrónica,900,Juan,Valencia

Filtrado final:

In [ ]:
# Clientes con compras > 1000
clientes_top = analisis_completo.groupby(['id_cliente', 'nombre_cliente'])['total'].sum()
clientes_top = clientes_top[clientes_top > 1000]
print(f"\nClientes con compras > 1000:\n{clientes_top}")

Clientes con compras > 1000:
id_cliente  nombre_cliente
2           Carlos            7280
Name: total, dtype: int64

### Manejo de Datos Faltantes y Outliers

Crear dataset con problemas realistas:

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

# Crear dataset con missing values y outliers
np.random.seed(42)
n = 1000

datos = pd.DataFrame({
    'id': range(1, n+1),
    'edad': np.random.normal(35, 10, n).clip(18, 80),  # Normal con límites
    'salario': np.random.lognormal(10, 0.5, n),  # Distribución log-normal
    'horas_trabajo': np.random.normal(40, 5, n).clip(20, 60),
    'satisfaccion': np.random.randint(1, 6, n),
    'departamento': np.random.choice(['IT', 'Ventas', 'Marketing', 'HR'], n)
})

# Introducir missing values
mask_missing = np.random.random(n) < 0.1  # 10% missing
datos.loc[mask_missing, 'salario'] = np.nan

mask_missing_horas = np.random.random(n) < 0.05  # 5% missing
datos.loc[mask_missing_horas, 'horas_trabajo'] = np.nan

# Introducir outliers
outlier_indices = np.random.choice(n, 20, replace=False)
datos.loc[outlier_indices[:10], 'salario'] = datos.loc[outlier_indices[:10], 'salario'] * 10  # Salarios extremos altos
datos.loc[outlier_indices[10:], 'horas_trabajo'] = np.random.choice([80, 90, 100], 10)  # Horas imposibles

print(f"Dataset creado: {datos.shape}")
print(f"Valores faltantes por columna:\n{datos.isnull().sum()}")

Dataset creado: (1000, 6)
Valores faltantes por columna:
id                0
edad              0
salario          95
horas_trabajo    46
satisfaccion      0
departamento      0
dtype: int64